### ISSUE TITLE
might be easier to install if it is on crates.io

### ISSUE THREAD

**Issue by chibby0ne** [Roger/tmux-hints#1]
First off, thanks for a great program! I use it everyday :)

Maybe might be better to install via crates.io as suggested here https://doc.rust-lang.org/book/2018-edition/ch14-04-installing-binaries.html

I might be able to help with this (or integrate it with travis if you would like).

Thanks again!

**Comment by lutostag** [comment]
Good idea @chibby0ne I'll take a stab at it, https://doc.rust-lang.org/cargo/reference/publishing.html seems like a good place to start ;)

**Comment by Roger** [comment]
done! :) https://github.com/Roger/tmux-hints/commit/46bbd3cc264100f17d3e8b29bdf5f1e994b5c054

**Comment by lutostag** [comment]
Thanks!
